---

- name: Modify net.ipv4.ip_forward config
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
- name: Add iptables record
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: {{ nat_gateway_output_interface }}
    jump: MASQUERADE
- name: Persist net.ipv4.ip_forward config
  lineinfile:
    path: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1
    state: present
- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present